# Generated by Django 5.2.4 on 2025-07-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory_app', '0001_initial'),
        ('users_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité Prévue')),
                ('quantite_produite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantité Produite')),
                ('date_debut', models.DateField(verbose_name='Date de Début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de Fin')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=50, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production_crees', to='users_app.utilisateur', verbose_name='Créé par')),
                ('produit_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production_fini', to='inventory_app.produitfini', verbose_name='Produit Fini à Produire')),
                ('produit_semi_fini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_production_semi_fini', to='inventory_app.produitsemifini', verbose_name='Produit Semi-Fini à Produire')),
            ],
            options={
                'verbose_name': 'Ordre de Production',
                'verbose_name_plural': 'Ordres de Production',
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit_parent', models.PositiveIntegerField(verbose_name='ID Produit Parent')),
                ('type_produit_parent', models.CharField(choices=[('semi_fini', 'Produit Semi-Fini'), ('fini', 'Produit Fini')], max_length=50, verbose_name='Type Produit Parent')),
                ('id_composant', models.PositiveIntegerField(verbose_name='ID Composant')),
                ('type_composant', models.CharField(choices=[('matiere', 'Matière Première'), ('semi_fini', 'Produit Semi-Fini')], max_length=50, verbose_name='Type Composant')),
                ('quantite_requise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité Requise')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('content_type_composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_produits_composant', to='contenttypes.contenttype')),
                ('content_type_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_produits_parent', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Nomenclature Produit',
                'verbose_name_plural': 'Nomenclatures Produits',
                'db_table': 'nomenclature_produits',
                'unique_together': {('content_type_parent', 'id_produit_parent', 'content_type_composant', 'id_composant')},
            },
        ),
        migrations.CreateModel(
            name='MatiereProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité Utilisée')),
                ('id_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_production', to='inventory_app.matierepremiere', verbose_name='Matière Première')),
                ('id_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_utilisee', to='production_app.production', verbose_name='Ordre de Production')),
            ],
            options={
                'verbose_name': 'Matière Utilisée en Production',
                'verbose_name_plural': 'Matières Utilisées en Production',
                'db_table': 'matieres_production',
                'unique_together': {('id_production', 'id_matiere')},
            },
        ),
    ]
