# Generated by Django 5.2.4 on 2025-07-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_app', '0001_initial'),
        ('users_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name="Nom de l'Entreprise")),
                ('personne_contact', models.CharField(blank=True, max_length=255, verbose_name='Personne de Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('en_production', 'En Production'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=50, verbose_name='Statut')),
                ('date_commande', models.DateField(verbose_name='Date de Commande')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de Livraison Prévue')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to='users_app.utilisateur', verbose_name='Créée par')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='sales_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_commandes', to='inventory_app.produitfini', verbose_name='Produit Fini')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sales_app.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de Commande',
                'verbose_name_plural': 'Articles de Commande',
                'db_table': 'articles_commande',
                'unique_together': {('id_commande', 'id_produit')},
            },
        ),
    ]
