# Generated by Django 5.2.4 on 2025-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name="Nom de l'Entreprise")),
                ('personne_contact', models.CharField(blank=True, max_length=255, verbose_name='Personne de Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('code_fournisseur', models.CharField(max_length=50, unique=True, verbose_name='Code Fournisseur')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseurs',
            },
        ),
    ]
