# Generated by Django 5.2.4 on 2025-07-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code_reference', models.CharField(max_length=100, unique=True, verbose_name='Code de Référence')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_min_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Niveau Min. Stock')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Est Archivé')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Matière Première',
                'verbose_name_plural': 'Matières Premières',
                'db_table': 'matieres_premieres',
            },
        ),
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code_reference', models.CharField(max_length=100, unique=True, verbose_name='Code de Référence')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_min_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Niveau Min. Stock')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Est Archivé')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Produit Fini',
                'verbose_name_plural': 'Produits Finis',
                'db_table': 'produits_finis',
            },
        ),
        migrations.CreateModel(
            name='ProduitSemiFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code_reference', models.CharField(max_length=100, unique=True, verbose_name='Code de Référence')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_min_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Niveau Min. Stock')),
                ('est_archive', models.BooleanField(default=False, verbose_name='Est Archivé')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Produit Semi-Fini',
                'verbose_name_plural': 'Produits Semi-Finis',
                'db_table': 'produits_semi_finis',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article', models.CharField(choices=[('matiere', 'Matière Première'), ('semi_fini', 'Produit Semi-Fini'), ('fini', 'Produit Fini')], max_length=50, verbose_name="Type d'Article")),
                ('id_article', models.PositiveIntegerField(verbose_name='ID Article')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('emplacement', models.CharField(max_length=255, verbose_name='Emplacement')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière Mise à Jour')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'unique_together': {('content_type', 'id_article', 'emplacement')},
            },
        ),
    ]
