# Generated by Django 5.2.4 on 2025-07-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory_app', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.entrepot', verbose_name='Entrepôt'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('content_type', 'id_article', 'entrepot')},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='emplacement',
        ),
    ]
