# Generated by Django 5.2.4 on 2025-07-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_stock_unique_together_stock_entrepot_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.entrepot', verbose_name='Entrepôt'),
        ),
    ]
