# Generated by Django 5.2.4 on 2025-07-28 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory_app', '0003_alter_stock_entrepot'),
        ('users_app', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('transfert', 'Transfert')], max_length=20, verbose_name='Type de Mouvement')),
                ('motif', models.CharField(choices=[('reception', 'Réception'), ('vente', 'Vente'), ('production', 'Production'), ('perte', 'Perte'), ('ajustement', 'Ajustement'), ('transfert', 'Transfert'), ('autre', 'Autre')], max_length=20, verbose_name='Motif')),
                ('id_article', models.PositiveIntegerField(verbose_name='ID Article')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du Mouvement')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de Contenu')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.entrepot', verbose_name='Entrepôt')),
                ('entrepot_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_source', to='warehouse.entrepot', verbose_name='Entrepôt Source')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_app.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'db_table': 'mouvements_stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
