# Generated by Django 5.2.4 on 2025-07-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_alter_stock_quantite_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='destination_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la Destination'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('fournisseur', 'Fournisseur'), ('entrepot', 'Entrepôt'), ('client', 'Client'), ('production', 'Production'), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Type de Destination'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='source_nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la Source'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='source_type',
            field=models.CharField(blank=True, choices=[('fournisseur', 'Fournisseur'), ('entrepot', 'Entrepôt'), ('client', 'Client'), ('production', 'Production'), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Type de Source'),
        ),
    ]
