# Generated by Django 5.2.4 on 2025-07-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_mouvementstock_destination_nom_and_more'),
        ('sales_app', '0002_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='client_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_client', to='sales_app.client', verbose_name='Client Destination'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='fournisseur_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_fournisseur', to='sales_app.fournisseur', verbose_name='Fournisseur Source'),
        ),
    ]
