# Generated by Django 5.2.4 on 2025-07-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_mouvementstock_client_destination_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='entrepot_destination_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_destination_entrepot', to='warehouse.entrepot', verbose_name='Entrepôt Destination'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='entrepot_source_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_source_entrepot', to='warehouse.entrepot', verbose_name='Entrepôt Source'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('entrepot', 'Entrepôt')], max_length=20, null=True, verbose_name='Type de Destination'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='source_type',
            field=models.CharField(blank=True, choices=[('fournisseur', 'Fournisseur'), ('entrepot', 'Entrepôt')], max_length=20, null=True, verbose_name='Type de Source'),
        ),
    ]
