# Generated by Django 5.2.4 on 2025-08-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='acces_tous_entrepots',
            field=models.BooleanField(default=False, help_text="Si activé, l'utilisateur a accès à tous les entrepôts. Sinon, seuls les entrepôts spécifiés sont accessibles.", verbose_name='Accès à tous les entrepôts'),
        ),
        migrations.CreateModel(
            name='UtilisateurEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict, help_text="Permissions spécifiques pour cet entrepôt (ex: {'can_read': True, 'can_write': True})", verbose_name='Permissions spécifiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_autorises', to='warehouse.entrepot', verbose_name='Entrepôt')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots_autorises', to='users_app.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Accès Utilisateur-Entrepôt',
                'verbose_name_plural': 'Accès Utilisateur-Entrepôt',
                'db_table': 'utilisateur_entrepot',
                'unique_together': {('utilisateur', 'entrepot')},
            },
        ),
    ]
