# Generated by Django 5.2.4 on 2025-08-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_utilisateur_acces_tous_entrepots_utilisateurentrepot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurentrepot',
            name='permissions',
        ),
        migrations.AddField(
            model_name='utilisateurentrepot',
            name='peut_lire',
            field=models.BooleanField(default=True, help_text="L'utilisateur peut voir les données de cet entrepôt", verbose_name='Peut lire'),
        ),
        migrations.AddField(
            model_name='utilisateurentrepot',
            name='peut_modifier',
            field=models.BooleanField(default=False, help_text="L'utilisateur peut modifier les données de cet entrepôt", verbose_name='Peut modifier'),
        ),
        migrations.AddField(
            model_name='utilisateurentrepot',
            name='peut_supprimer',
            field=models.BooleanField(default=False, help_text="L'utilisateur peut supprimer les données de cet entrepôt", verbose_name='Peut supprimer'),
        ),
    ]
