# Generated by Django 5.2.4 on 2025-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_utilisateurentrepot_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
    ]
