# Generated by Django 5.2.4 on 2025-08-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_role_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='acces_tous_entrepots',
            field=models.BooleanField(default=False, help_text="Si activé, l'utilisateur a accès à tous les entrepôts. Si désactivé, vous devez spécifier les entrepôts individuels ci-dessous.", verbose_name='Accès à tous les entrepôts'),
        ),
    ]
