# Generated by Django 4.2.23 on 2025-09-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_utilisateur_acces_tous_entrepots'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut_equipe',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('vacances', 'En vacances'), ('maladie', 'En arrêt maladie'), ('formation', 'En formation')], default='actif', help_text="Statut actuel de l'utilisateur dans l'équipe", max_length=20, verbose_name='Statut équipe'),
        ),
    ]
