# Generated by Django 5.2.4 on 2025-07-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('id_entite', models.PositiveIntegerField(verbose_name='ID Entité')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('id_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='users_app.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'Activité",
                'verbose_name_plural': "Historiques d'Activités",
                'db_table': 'historique_activites',
                'ordering': ['-horodatage'],
            },
        ),
    ]
