# Generated by Django 5.2.4 on 2025-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'entrepôt")),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'db_table': 'entrepots',
            },
        ),
    ]
